#Primary Database Configuration
main.datasource.url=jdbc:postgresql://localhost:5432/jmix_hrm
main.datasource.username=postgres
main.datasource.password=J@yesh123456
main.liquibase.change-log=com/company/jmix_hrm/liquibase/changelog.xml

jmix.core.additional-stores=secondary
secondary.datasource.url=jdbc:mysql://localhost:3306/jmix_hrm_address?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
secondary.datasource.username=root
secondary.datasource.password=J@yesh123456
secondary.liquibase.change-log=com/company/jmix_hrm/liquibase/secondary-changelog.xml

jmix.ui.login-view-id=LoginView
jmix.ui.main-view-id=MainView
jmix.ui.menu-config=com/company/jmix_hrm/menu.xml
jmix.ui.composite-menu=true

ui.login.defaultUsername=admin
ui.login.defaultPassword=admin

jmix.core.available-locales=en,de,it

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=false
# Enable colors in logs
spring.output.ansi.enabled=always
# 'debug' level logs SQL generated by EclipseLink ORM
logging.level.eclipselink.logging.sql=info
# 'debug' level logs data store operations
logging.level.io.jmix.core.datastore=info
# 'debug' level logs access control constraints
logging.level.io.jmix.core.AccessLogger=debug
# 'debug' level logs all Jmix debug output
logging.level.io.jmix=info
# 'debug' or 'trace' levels help to troubleshoot security problems
logging.level.org.springframework.security=info
#logging.level.org.springframework.security=DEBUG
logging.level.org.atmosphere=warn


#Email Configuration
#specifying which server to connect
spring.mail.host=smtp.gmail.com
#this port will be used to connect to smtp server
spring.mail.port=587
#simple mail transfer protocol to be used for sending email
spring.mail.protocol=smtp
#username and password for authentication
spring.mail.username=jb.bandi.direction@gmail.com
spring.mail.password=uzcm ufer vnnr rdkb
#enables authentication, without this g-mail will not allow to send email
spring.mail.properties.mail.smtp.auth=true
#makes the connection secure (tls - transport layer security)
spring.mail.properties.mail.smtp.starttls.enable=true


#LDAP Configuration
# specifying the ldap server url
jmix.ldap.urls=ldap://localhost:10389/
#specifying the base dn (Distinguished Name) - Root directory
jmix.ldap.base-dn=ou=system
#specifying the system admin dn and password - Because the system admin credentials are required for connecting to ldap server
jmix.ldap.manager-dn=uid=admin,ou=system
jmix.ldap.manager-password=secret
#specifying in which directory to search users
#jmix.ldap.user-search-base = ou=users
#specifying the attribute to check in user entry
jmix.ldap.user-search-filter=(uid={0})
#jmix.ldap.default-roles=ui-minimal
#jmix.ldap.group-role-attribute=employeeType
#jmix.ldap.default-roles=system-full-access
#jmix.ldap.default-roles=ui-minimal,manager-resource-role